frontend:
  name: frontend
  image: santoshpalla27/3-tier:frontend-6
  minReplicas: 1
  maxReplicas: 10

ingress:
  domain: santosh.website


database:
  name: mongodb
  image: mongo:latest
  replicas: 1
  