---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ values.frontend.name }}
    spec:
      containers:
      - name: {{ values.frontend.name }}
        image: {{ values.frontend.image }}
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_API_URL
        resources:
          requests:
            cpu: "200m"      # Requesting 200 milli-CPU
          limits:
            cpu: "500m"      # Limiting the container to 500 milli-CPU
---
apiVersion: v1
kind: Service
metadata:
  name: {{ values.frontend.name }}
spec:
  ports:
  - port: 5173
    targetPort: 5173
  selector:
    app: frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ values.frontend.name }}
  minReplicas: {{ values.frontend.minReplicas }}
  maxReplicas: {{ values.frontend.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
